# Generated by Django 5.2.17 on 2026-08-19 23:55

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_validateur_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    group, created = Group.objects.get_or_create(name="Validateurs")
    
    # We want to give them access to manage resultats and imports
    # But since apps.get_model requires the actual models, we can just filter by app_label
    permissions = Permission.objects.filter(
        content_type__app_label__in=['resultats', 'imports', 'filieres']
    )
    group.permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resultats', '0001_initial'),
        ('imports', '0001_initial'),
        ('filieres', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_validateur_group),
    ]
