# Generated by Django 5.2a1 on 2026-08-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "a_des_specialites",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher si la filière n'a pas de spécialités (ex: Secrétariat de Direction)",
                    ),
                ),
                (
                    "specialite_unique_auto",
                    models.BooleanField(
                        default=False,
                        help_text="Si vrai et qu'il n'y a pas de spécialités, une spécialité 'Tronc Commun' ou du nom de la filière est implicite",
                    ),
                ),
                (
                    "niveaux",
                    models.ManyToManyField(related_name="filieres", to="core.niveau"),
                ),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Specialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=20)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialites",
                        to="filieres.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
                "ordering": ["filiere", "nom"],
                "unique_together": {("nom", "filiere")},
            },
        ),
        migrations.CreateModel(
            name="UE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("credits", models.PositiveSmallIntegerField(default=0)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ues",
                        to="filieres.filiere",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ues",
                        to="core.semestre",
                    ),
                ),
                (
                    "specialite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ues",
                        to="filieres.specialite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unité d'Enseignement (UE)",
                "verbose_name_plural": "Unités d'Enseignement (UE)",
                "unique_together": {("code", "semestre", "filiere", "specialite")},
            },
        ),
        migrations.CreateModel(
            name="EC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecs",
                        to="filieres.ue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément Constitutif (EC)",
                "verbose_name_plural": "Éléments Constitutifs (EC)",
                "unique_together": {("code", "ue")},
            },
        ),
    ]
