# Generated by Django 5.2.17 on 2026-08-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='filieres.anneeacademique')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('a_des_specialites', models.BooleanField(default=True)),
                ('specialite_unique_auto', models.BooleanField(default=False)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='filieres.niveau')),
            ],
            options={
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('stage', 'Stage')], default='normal', max_length=30)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='filieres.filiere')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='filieres.filiere')),
            ],
            options={
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('normale', 'Session normale'), ('rattrapage', 'Rattrapage'), ('ajournement', 'Ajournement'), ('re_enjambement', 'Ré-enjambement')], max_length=30)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='filieres.semestre')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='filieres.specialite')),
            ],
            options={
                'verbose_name': 'Session de résultats',
                'verbose_name_plural': 'Sessions de résultats',
            },
        ),
    ]
