# Generated by Django 5.2a1 on 2026-08-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeAcademique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.CharField(
                        help_text="Ex: 2023-2024", max_length=9, unique=True
                    ),
                ),
                ("est_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Année académique",
                "verbose_name_plural": "Années académiques",
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: L1, L2, M1", max_length=50, unique=True
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(help_text="Ex: Semestre 1", max_length=50)),
                ("numero", models.PositiveSmallIntegerField(default=1)),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestres",
                        to="core.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["numero"],
                "unique_together": {("nom", "niveau")},
            },
        ),
        migrations.CreateModel(
            name="SessionResultat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_session",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Normale"),
                            ("RATTRAPAGE", "Rattrapage"),
                            ("AJOURNEMENT", "Ajournement"),
                        ],
                        default="NORMALE",
                        max_length=20,
                    ),
                ),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.anneeacademique",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de résultat",
                "verbose_name_plural": "Sessions de résultat",
                "unique_together": {("type_session", "annee_academique", "semestre")},
            },
        ),
    ]
