# Generated by Django 5.2a1 on 2026-08-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("filieres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=150)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiants",
                        to="filieres.filiere",
                    ),
                ),
                (
                    "specialite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etudiants",
                        to="filieres.specialite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
                "ordering": ["nom", "prenoms"],
            },
        ),
        migrations.CreateModel(
            name="ResultatUE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moyenne_ue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Moyenne figée lors de l'import, non recalculée dynamiquement.",
                        max_digits=5,
                    ),
                ),
                ("est_valide", models.BooleanField(default=False)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats_ue",
                        to="resultats.etudiant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats_ue",
                        to="core.sessionresultat",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="filieres.ue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat UE",
                "verbose_name_plural": "Résultats UE",
                "unique_together": {("etudiant", "ue", "session")},
            },
        ),
        migrations.CreateModel(
            name="NoteEC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="filieres.ec",
                    ),
                ),
                (
                    "resultat_ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_ec",
                        to="resultats.resultatue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note EC",
                "verbose_name_plural": "Notes EC",
                "unique_together": {("resultat_ue", "ec")},
            },
        ),
    ]
