# Generated by Django 5.2.17 on 2026-08-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filieres", "0001_initial"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("annee_promo", models.CharField(blank=True, max_length=10, null=True)),
                ("nom", models.CharField(max_length=150)),
                ("prenom", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "etudiant",
                "indexes": [
                    models.Index(
                        fields=["matricule"], name="etudiant_matricu_00f209_idx"
                    ),
                    models.Index(
                        fields=["nom", "prenom"], name="etudiant_nom_a700ce_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("nom", models.CharField(max_length=200)),
                ("credits", models.PositiveIntegerField()),
                (
                    "fichier_pdf_archive",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("date_publication", models.DateField(blank=True, null=True)),
                ("statut", models.CharField(default="brouillon", max_length=20)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filieres.sessionresultat",
                    ),
                ),
            ],
            options={
                "db_table": "ue",
            },
        ),
        migrations.CreateModel(
            name="ResultatUE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moyenne_ue", models.DecimalField(decimal_places=2, max_digits=4)),
                ("statut", models.CharField(max_length=5)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resultats.etudiant",
                    ),
                ),
                (
                    "import_fichier",
                    models.ForeignKey(
                        blank=True,
                        db_column="import_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="imports.importfichier",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resultats.ue"
                    ),
                ),
            ],
            options={
                "db_table": "resultat_ue",
            },
        ),
        migrations.CreateModel(
            name="EC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("nom", models.CharField(max_length=200)),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resultats.ue"
                    ),
                ),
            ],
            options={
                "db_table": "ec",
            },
        ),
        migrations.CreateModel(
            name="NoteEC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "ec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resultats.ec"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resultats.etudiant",
                    ),
                ),
                (
                    "import_fichier",
                    models.ForeignKey(
                        blank=True,
                        db_column="import_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="imports.importfichier",
                    ),
                ),
            ],
            options={
                "db_table": "note_ec",
                "indexes": [
                    models.Index(fields=["etudiant"], name="note_ec_etudian_e3eb3f_idx")
                ],
                "unique_together": {("etudiant", "ec")},
            },
        ),
        migrations.AddIndex(
            model_name="ue",
            index=models.Index(fields=["session"], name="ue_session_7bc4e3_idx"),
        ),
        migrations.AddIndex(
            model_name="resultatue",
            index=models.Index(
                fields=["etudiant"], name="resultat_ue_etudian_b99e35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resultatue",
            unique_together={("etudiant", "ue")},
        ),
    ]
