# Generated by Django 5.2.17 on 2026-08-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filieres', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('annee_promo', models.CharField(blank=True, max_length=10)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='resultats_e_nom_07e6fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('credits', models.PositiveIntegerField()),
                ('fichier_pdf_archive', models.FileField(blank=True, null=True, upload_to='pv_archives/')),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='filieres.sessionresultat')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UE',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs', to='resultats.ue')),
            ],
            options={
                'verbose_name': 'EC',
                'verbose_name_plural': 'EC',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NoteEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='resultats.ec')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ec', to='resultats.etudiant')),
                ('import_fichier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_ec', to='imports.importfichier')),
            ],
            options={
                'verbose_name': 'Note EC',
                'verbose_name_plural': 'Notes EC',
                'unique_together': {('etudiant', 'ec')},
            },
        ),
        migrations.CreateModel(
            name='ResultatUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_ue', models.DecimalField(decimal_places=2, max_digits=4)),
                ('statut', models.CharField(choices=[('V', 'Validé'), ('NV', 'Non validé'), ('V*', 'Validé*')], max_length=5)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ue', to='resultats.etudiant')),
                ('import_fichier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_ue', to='imports.importfichier')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='resultats.ue')),
            ],
            options={
                'verbose_name': 'Résultat UE',
                'verbose_name_plural': 'Résultats UE',
                'unique_together': {('etudiant', 'ue')},
            },
        ),
    ]
