# Generated by Django 5.2.17 on 2026-08-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0002_historicalec_historicaletudiant_historicalnoteec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaletudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
