# Generated by Django 5.2.17 on 2026-08-22 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0003_etudiant_email_historicaletudiant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='resultats.etudiant')),
            ],
            options={
                'verbose_name': 'Signalement / Contact',
                'verbose_name_plural': 'Signalements / Contacts',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
