# Generated by Django 5.2.17 on 2026-08-16 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('config_colonnes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=300)),
                ('fichier', models.FileField(upload_to='imports_bruts/')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('applique', 'Appliqué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.mappingtemplate')),
            ],
            options={
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='LigneBrute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('donnees_brutes', models.JSONField()),
                ('statut_traitement', models.CharField(default='en_attente', max_length=20)),
                ('import_fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='imports.importfichier')),
            ],
            options={
                'ordering': ['numero_ligne'],
            },
        ),
    ]
