# Generated by Django 5.2a1 on 2026-08-21 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "mapping_json",
                    models.JSONField(
                        help_text="Dictionnaire associant les champs de la base de données aux colonnes du fichier Excel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de mapping",
                "verbose_name_plural": "Modèles de mapping",
            },
        ),
        migrations.CreateModel(
            name="ImportFichier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="imports/%Y/%m/%d/")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de mapping"),
                            ("MAPPING_VALIDE", "Mapping validé"),
                            ("TRAITEMENT", "En cours de traitement"),
                            ("TERMINE", "Terminé avec succès"),
                            ("ERREUR", "Erreur"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="core.sessionresultat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier d'import",
                "verbose_name_plural": "Fichiers d'import",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LigneBrute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ligne", models.PositiveIntegerField()),
                ("donnees_json", models.JSONField()),
                ("est_valide", models.BooleanField(default=False)),
                ("erreurs", models.JSONField(blank=True, null=True)),
                (
                    "import_fichier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_brutes",
                        to="imports.importfichier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne brute",
                "verbose_name_plural": "Lignes brutes",
                "ordering": ["import_fichier", "numero_ligne"],
                "unique_together": {("import_fichier", "numero_ligne")},
            },
        ),
    ]
