# Generated by Django 5.2.17 on 2026-08-20 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("config_colonnes", models.JSONField()),
            ],
            options={
                "db_table": "mapping_template",
            },
        ),
        migrations.CreateModel(
            name="ImportFichier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_fichier", models.CharField(max_length=300)),
                ("date_import", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(default="en_attente", max_length=20)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="imports.mappingtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "import_fichier",
            },
        ),
        migrations.CreateModel(
            name="LigneBrute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ligne", models.IntegerField()),
                ("donnees_brutes", models.JSONField()),
                (
                    "statut_traitement",
                    models.CharField(default="en_attente", max_length=20),
                ),
                (
                    "import_fichier",
                    models.ForeignKey(
                        db_column="import_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imports.importfichier",
                    ),
                ),
            ],
            options={
                "db_table": "ligne_brute",
            },
        ),
    ]
