# Generated by Django 5.2.17 on 2026-08-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_historicalimportfichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebrute',
            name='message_erreur',
            field=models.TextField(blank=True, default=''),
        ),
    ]
