# Generated by Django 5.2.17 on 2026-08-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filieres', '0002_historicalfiliere'),
        ('imports', '0003_lignebrute_message_erreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportfichier',
            name='fichier_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalimportfichier',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filieres.sessionresultat'),
        ),
        migrations.AddField(
            model_name='importfichier',
            name='fichier_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='importfichier',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='filieres.sessionresultat'),
        ),
    ]
